# Generated by Django 4.1.7 on 2023-03-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('contact', models.CharField(max_length=122)),
                ('frm', models.CharField(max_length=122)),
                ('to', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
