# Generated by Django 4.1.7 on 2023-03-22 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0002_book_flight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book_flight',
        ),
    ]
